### ISSUE TITLE
Custom SSL Certificate causing restreamer to crash

### ISSUE THREAD

**Issue by x390** [datarhei/restreamer#425] opened 2022-10-10 12:14 UTC
Restreamer crashes when attempting to use a custom ssl certificate from acme.sh.

```
restreamer    | ts=2022-10-10T11:27:50Z level=INFO component="Import" msg="Database import" version="v1"
restreamer    | ts=2022-10-10T11:27:50Z level=INFO component="Import" msg="Checking for database ..." version="v1"
restreamer    | ts=2022-10-10T11:27:50Z level=INFO component="Import" msg="Database doesn't exist and nothing will be imported" database="/core/config/v1.json" version="v1"
restreamer    | ts=2022-10-10T11:27:50Z level=INFO component="Core" application="datarhei-core" arch="linux/amd64" branch="main" build="2022-09-30T13:54:39Z" commit="bae68f8d31c07f403fd3ca7f350a1e0a7dbe7836" compiler="go1.18.6" license="Apache License Version 2.0" repository="https://github.com/datarhei/core" version="16.10.1"
restreamer    | ts=2022-10-10T11:27:50Z level=INFO component="HTTPS" msg="Server started" address=":8181"
restreamer    | ts=2022-10-10T11:27:50Z level=INFO component="RTMP" msg="Server started" address=":1935"
restreamer    | panic: runtime error: invalid memory address or nil pointer dereference
restreamer    |         panic: runtime error: invalid memory address or nil pointer dereference
restreamer    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xd41be5]
restreamer    | 
restreamer    | goroutine 23 [running]:
restreamer    | github.com/datarhei/core/v16/app/api.(*api).start.func7.1()
restreamer    |         /dist/core/app/api/api.go:1004 +0x25
restreamer    | panic({0xe0d420, 0x1f35480})
restreamer    |         /usr/local/go/src/runtime/panic.go:838 +0x207
restreamer    | github.com/datarhei/core/v16/app/api.(*api).start.func7()
restreamer    |         /dist/core/app/api/api.go:1012 +0xe0
restreamer    | created by github.com/datarhei/core/v16/app/api.(*api).start
restreamer    |         /dist/core/app/api/api.go:1000 +0x588c
restreamer exited with code 2
```

**What I have tried to do to fix the issue:**
1. Setting host.name to my domain name
2. setting host.auto to `false`
3. Checking if the permissions are correct
4. Using the openssl command from the [guide](https://github.com/datarhei/core#tls--https) in core repo

**Comment by jstabenow** [comment] 2022-10-10 19:46
@x390 Should be fixed in dev image. Please try:
datarhei/restreamer:dev

Thx.

**Comment by jstabenow** [comment] 2022-10-18 15:10
@x390 does it work?

**Comment by LeXonJe** [comment] 2022-10-23 19:25
Hey @jstabenow,

I've had the same issue and I can luckily report that RTMPS is working now with a custom certificate as intended using the dev release. The server doesn't crash on startup anymore.

Thank you for the fix. 😄

**Comment by LeXonJe** [comment] 2022-10-23 19:38
A quick follow-up:

RTMPS is functional (Tested with OBS). However, the settings menu for rtmp is now bugged due to it saying "RTMPS server can only be enabled if TLS is enabled" when I try to save a new token, etc. I also can't edit the RTMPS or HTTPS port from the web ui. I think this is happening because "Let's Encrypt certification" is turned off. For now the workaround is to directly edit the config.json.

**Closed as completed** 2022-11-09 14:18 UTC
Labels: bug
