### ISSUE TITLE
armv7 docker build failing on curl 

### ISSUE THREAD

**Issue by jdw003** [datarhei/restreamer#261] opened 2021-04-17 04:18 UTC
restreamer-arm32v7 builds are failing due to issue with curl certificates (error text below). Note that the error is not thrown when curl commands are run directly from a `arm32v7/debian:10.4-slim` container on rpi so this is specific to the docker build process.

```
#6 1.250 curl: (60) SSL certificate problem: unable to get local issuer certificate
#6 1.251 More details here: https://curl.haxx.se/docs/sslcerts.html
```

The issue is resolved by replacing all `curl -OL` refs with `wget` or `curl -k`

**Comment by ioppermann** [comment] 2021-04-27 15:51
@jdw003 Hmm, unfortunately, I couldn't reproduce this.

**Comment by svenerbeck** [comment] 2022-06-03 21:14
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.

**Closed** 2022-06-06 09:35 UTC
