### ISSUE TITLE
Wrong viewer count

### ISSUE THREAD

**Issue by ftrescue** [datarhei/restreamer#394] opened 2022-07-28 17:48 UTC
think there is a bug as just updated to the latest and on making a new stream all streams says 2 people watching 
![image](https://user-images.githubusercontent.com/96438569/181603825-654965aa-0221-4be9-b32e-21a331d95844.png)

**Comment by ioppermann** [comment] 2022-07-29 07:50
Most of the time the browser is opening two connections to the stream at the beginning and then immediately drops one. This is counted as 2 viewers. After a few seconds (~30 seconds) the seconds viewer will disappear when the session expires.

**Comment by ftrescue** [comment] 2022-07-29 09:44
I did think that but unfortunately mine has not dropped back to one they’re all set at two

**Comment by ioppermann** [comment] 2022-07-29 11:48
I could reproduce this. Do you send the stream via RTMP to Restreamer? What is your setup?

**Comment by ftrescue** [comment] 2022-07-30 00:28
rtsp local to streamer

**Comment by ftrescue** [comment] 2022-08-01 16:45
I'm thing its running 2 times on server as how do i check this ? as youtube is there but no video

**Comment by ftrescue** [comment] 2022-08-01 17:43
just run the docker ps -a  and restreamer is only running once but there might be 2 folders in the back eg db and jenson

**Comment by svenerbeck** [comment] 2022-11-15 09:40
Dear @ftrescue 
We are closing your issue #394.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team

**Closed as completed by svenerbeck** 2022-11-15 09:40 UTC
Labels: bug
