### ISSUE TITLE
RTSP stream always on without clients?

### ISSUE THREAD

**Issue by bygpepa** [datarhei/restreamer#680] opened 2024-01-24 09:33 UTC
**Subject of the issue**
I tried to search answers for this, but to no avail.
I set up two RTSP streams from cameras and it all works. But a day later I checked network activity for the machine and it was grabbing the stream from the cameras the whole 24 hours, even there were no clients to watch it. 
Is this a normal behaviour for restreamer? Is it possible to configure it in a senzible way that it would only grab the rtsp stream when there are some clients to watch it?
I want to set up maybe 100 streams, but if they are all always active, it would overload the network. I don't expect so many clients to see it all the time.
Thank you for any answer, either that it is a feature, or that it can be configured somehow (I didn't find it).
Josef.

**Your environment**
Debian 11 (on linode), setup by docker.

**Files**

**Steps to reproduce**
Just setup a rtsp stream, don't watch it and monitor network load.

**Awesome** ⭐⭐⭐⭐⭐

**Expected behavior**
I would expect that when some client appears to watch the stream, restreamer would initiate the stream from the camera. And then again when number of clients goes to zero, it would stop grabbing the stream from the camera.

**Actual behavior**
Restreamer is grabbing the stream from the camera even though no one is watching.

**Comment by ioppermann** [comment] 2024-01-26 15:11
The actual behavior is intentional. The RTSP stream is pulled from the camera, regardles if someone is watching or not.

We added this issue as feature request. It's a duplicate of #520.

**Closed as completed by ioppermann** 2024-01-26 15:11 UTC
Labels: duplicate, enhancement
