### ISSUE TITLE
When attempting to use HEVC encoder in OBS, Restreamer fails to pick up the output.

### ISSUE THREAD

**Issue by twilwa** [datarhei/restreamer#654] opened 2023-12-08 19:46 UTC
**Describe the bug**
When attempting to use HEVC encoder in OBS, Restreamer fails to pick up the output.

**To Reproduce**
Change output on OBS to HEVC (either Simple or Advanced)
Attempt to connect to any streaming service.

**Expected behavior**
Successfully able to connect.

**Screenshots**
Logs:
@1702063572 ffmpeg version 5.1.3-datarhei Copyright (c) 2000-2022 the FFmpeg developers
@1702063572   built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
@1702063572   configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libv4l2 --enable-v4l2_m2m --enable-libfreetype --enable-alsa --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
@1702063572   libavutil      57. 28.100 / 57. 28.100
@1702063572   libavcodec     59. 37.100 / 59. 37.100
@1702063572   libavformat    59. 27.100 / 59. 27.100
@1702063572   libavdevice    59.  7.100 / 59.  7.100
@1702063572   libavfilter     8. 44.100 /  8. 44.100
@1702063572   libswscale      6.  7.100 /  6.  7.100
@1702063572   libswresample   4.  7.100 /  4.  7.100
@1702063572   libpostproc    56.  6.100 / 56.  6.100
@1702063573 Input #0, flv, from 'rtmp://localhost:1935/667f7214-985a-476e-9eff-46bea6e70169.stream':
@1702063573   Metadata:
@1702063573     5.1             : false
@1702063573     3.1             : false
@1702063573     fileSize        : 0
@1702063573     2.1             : false
@1702063573     4.0             : false
@1702063573     7.1             : false
@1702063573     encoder         : obs-output module (libobs version 30.0.0)
@1702063573     audiochannels   : 2
@1702063573     4.1             : false
@1702063573   Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
@1702063573   Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 163 kb/s
@1702063573 Stream map '0:1' matches no streams.
@1702063573 To ignore this, add a trailing '?' to the map.

Banner:
ffmpeg version 5.1.3-datarhei Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libv4l2 --enable-v4l2_m2m --enable-libfreetype --enable-alsa --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flv, from 'rtmp://localhost:1935/667f7214-985a-476e-9eff-46bea6e70169.stream':
  Metadata:
    3.1             : false
    fileSize        : 0
    2.1             : false
    4.0             : false
    7.1             : false
    encoder         : obs-output module (libobs version 30.0.0)
    audiochannels   : 2
    4.1             : false
    5.1             : false
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 163 kb/s
Stream map '0:1' matches no streams.
To ignore this, add a trailing '?' to the map.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home, WSL2 Ubuntu 22.04

**Additional context**
In doing some initial testing & following the steps on the wiki for h.265 (attempting to adapt the instructions to an OBS stream as opposed to an IP camera, so I might be doing something wrong there), it appears that when the HEVC encoder is enabled, no video is received by the RTMP server, but when I change back to 264 (hardware or non-hardware), it picks it up again.

Let me know if there's an additional information I can provide.

## Business inquiries
**We provide support for commercial requirements with professional support, agile software development, and consulting.** If you have a commercial request, be it a bug or a feature enhancement, please contact us directly at support@datarhei.com.

**Comment by ioppermann** [comment] 2023-12-09 07:58
Duplicate of #637

**Closed as completed by ioppermann** 2023-12-09 07:58 UTC
Labels: bug
