### ISSUE TITLE
How to Configure a Virtual Camera with Restreamer

### ISSUE THREAD

**Issue by Sadoharu** [datarhei/restreamer#614] opened 2023-09-09 04:44 UTC
Hello,

I am running Restreamer v2.6.0 in a Docker container on my system. The container is running in privileged mode. I am trying to add a virtual camera (VirtualCam platform:v4l2loopback-000 /dev/video2) as an input source to Restreamer, but I am facing difficulties in getting it to work.

I have checked that the virtual camera is available on my host system, but it doesn't seem to be recognized by Restreamer.

Could you please guide me on how to properly configure Restreamer to use a virtual camera as an input source? Any help would be greatly appreciated.

Thank you!

**Comment by ioppermann** [comment] 2023-10-13 13:31
You have to start the docker container with the `--privileged` option. With this all devices from the host system will be available in the docker container. Then Restreamer will be able to detect them.

I tested it on a Raspberry Pi4 B on a freshly installed Raspbian bookworm 64 bit. First, I installed the `v4l2loopback` driver:
```
sudo apt update && sudo apt install raspberrypi-kernel-headers
curl -LO https://github.com/umlaeute/v4l2loopback/archive/refs/tags/v0.12.7.tar.gz
tar xzf v0.12.7.tar.gz && cd v4l2loopback-0.12.7
make && sudo make install
```

Then I created a loopback device:
```
sudo depmod -a
sudo modprobe v4l2loopback devices=1
```

And confirmed with:

```
v4l2-ctl --list-devices

bcm2835-codec-decode (platform:bcm2835-codec):
	/dev/video10
	/dev/video11
	/dev/video12
	/dev/video18
	/dev/video31
	/dev/media0

bcm2835-isp (platform:bcm2835-isp):
	/dev/video13
	/dev/video14
	/dev/video15
	/dev/video16
	/dev/video20
	/dev/video21
	/dev/video22
	/dev/video23
	/dev/media3
	/dev/media4

unicam (platform:fe801000.csi):
	/dev/video0
	/dev/video1
	/dev/media2

rpivid (platform:rpivid):
	/dev/video19
	/dev/media1

Dummy video device (0x0000) (platform:v4l2loopback-000):
	/dev/video2
```

Starting the Restreamer docker image with the `--privileged` option:
```
sudo docker run --detach --rm --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest
```

In a separate console window, I started `ffmpeg` in order to feed some video into the loopback device:
```
ffmpeg -f lavfi -re -i testsrc2=size=1280x720:r=25 -codec:v rawvideo -pix_fmt yuv420p -f v4l2 /dev/video2
```

In the "Video setup" I select "Hardware Device" and then choose the listed loopback device
![image](https://github.com/datarhei/restreamer/assets/57445/24257a72-afe0-439b-a929-d60692337d6e)
and press on "Next".

It will detect the stream and gives me the option to encode it to H264:
![image](https://github.com/datarhei/restreamer/assets/57445/5b72cbb7-f133-411e-8c83-29ef42fd6ce6)

It seems to work. The key thing is, that you have to start the Restreamer docker container with the `--privileged` option and to restart the container in case you created the loopback device after you already started the Restreamer container.

**Comment by svenerbeck** [comment] 2024-01-05 11:32
Hello @Sadoharu 

We are closing your ticket https://github.com/datarhei/restreamer/issues/614.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

**Closed as completed by svenerbeck** 2024-01-05 11:32 UTC
Labels: help wanted, question, configuration
